# File: urls.py
# Description: This file contains the Django url statements.
# Author(s): Team Suites (1)

# imports
from django.conf.urls import url
from . import views
from django.urls import path

# url statements
app_name = 'MDTouch'
urlpatterns = [
    #url(r'^$',views.index, name='getstarted'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.registerP, name='registerP'),
    url(r'^register/create$', views.createPLogIn, name='createPLogIn'),
    url(r'^password/$', views.password, name='password'),
    url(r'^password/changepass/$', views.changePass, name='changepass'),
    url(r'^verify/$', views.verify, name='verify'),
    url(r'^home/$', views.home, name='home'),
    url(r'^home/registerDN$', views.registerDN, name='registerDN'),
    url(r'^home/registerDN/createDN$', views.createDNLogIn, name='createDNLogIn'),
    url(r'^information/$', views.information, name='information'),
    url(r'^information/updatePro$', views.updatePro, name='updatePro'),
    url(r'^information/updatePro/updateProInfo$', views.updateProInfo, name='updateProInfo'),
    url(r'^information/updateMed/(?P<pat_id>[0-9]+)/', views.updateMed, name='updateMed'),
    url(r'^information/updateMed/updateMedInfo/(?P<pat_id>[0-9]+)/', views.updateMedInfo, name='updateMedInfo'),
    url(r'^information/export$', views.export, name='export'),
    url(r'^information/tests/(?P<pat_id>[0-9]+)/', views.tests, name='tests'),
    url(r'^information/tests/createTest/(?P<pat_id>[0-9]+)/', views.createTest, name='createTest'),
    url(r'^information/tests/createTest/createTestInfo/(?P<pat_id>[0-9]+)/', views.createTestInfo, name='createTestInfo'),
    url(r'^information/tests/releaseTest/(?P<test_id>[0-9]+)/', views.releaseTest, name='releaseTest'),
    url(r'^information/testDetails/(?P<test_id>[0-9]+)/', views.testDetails, name='testDetails'),
    url(r'^information/discharge/(?P<pat_id>[0-9]+)/', views.discharge, name='discharge'),
    url(r'^information/admission/(?P<pat_id>[0-9]+)/(?P<emp_id>[0-9]+)/', views.admission, name='admission'),
    url(r'^information/transfer/(?P<pat_id>[0-9]+)/(?P<emp_id>[0-9]+)/', views.transfer, name='transfer'),
    url(r'^appointments/$', views.appointments, name='appointments'),
    url(r'^appointments/createAppt$', views.createAppt, name='createAppt'),
    url(r'^appointments/createAppt/createApptInfo$', views.createApptInfo, name="createApptInfo"),
    url(r'^appointments/updateAppt/(?P<appt_id>[0-9]+)/', views.updateAppt, name='updateAppt'),
    url(r'^appointments/updateAppt/updateApptInfo/(?P<appt_id>[0-9]+)/', views.updateApptInfo, name='updateApptInfo'),
    url(r'^appointments/cancelAppt/(?P<appt_id>[0-9]+)/', views.cancelAppt, name='cancelAppt'),
    url(r'^prescriptions/$', views.prescriptions, name='prescriptions'),
    url(r'^prescriptions/createPres$', views.createPres, name='createPres'),
    url(r'^prescriptions/createPres/createPresInfo$', views.createPresInfo, name="createPresInfo"),
    url(r'^prescriptions/updatePres/(?P<pres_id>[0-9]+)/', views.updatePres, name='updatePres'),
    url(r'^prescriptions/updatePres/updatePresInfo/(?P<pres_id>[0-9]+)/', views.updatePresInfo, name='updatePresInfo'),
    url(r'^prescriptions/removePres/(?P<pres_id>[0-9]+)/', views.removePres, name='removePres'),
    url(r'^calendar/$', views.calendar, name='calendar'),
    url(r'^messages/$', views.messages, name='messages'),
    url(r'^messages/createMess/$', views.createMess, name='createMess'),
    url(r'^messages/createMess/createMessInfo/(?P<mess_id>-1)/', views.createMessInfo, name="createMessInfo"),
    url(r'^messages/replyMess/(?P<mess_id>[0-9]+)/', views.replyMess, name='replyMess'),
    url(r'^messages/replyMess/createMessInfo/(?P<mess_id>[0-9]+)/', views.createMessInfo, name="createMessInfo"),
    url(r'^messages/viewMess/(?P<mess_id>[0-9]+)/', views.viewMess, name='viewMess'),
    url(r'^messages/deleteMess/(?P<mess_id>[0-9]+)/', views.deleteMess, name='deleteMess'),
    url(r'^log/$', views.log, name='log'),
    url(r'^statistics/$', views.statistics, name='statistics'),
    url(r'^logOut/$', views.logOut, name='logOut'),
    url(r'events/$',views.getevents,name='event'),
    ##########API#####################
    path('api/hospital/', views.hospital_list),
    path('api/hospital/<int:pk>', views.hospital_detail),
    path('api/emergencycontact/', views.emergencycontact_list),
    path('api/emergencycontact/<int:pk>', views.emergencycontact_detail),
    path('api/patient/', views.patient_list),
    path('api/patient/<int:pk>', views.patient_detail),
    path('api/specialization/', views.specialization_list),
    path('api/specialization/<int:pk>', views.specialization_detail),
    path('api/qualification/', views.qualification_list),
    path('api/qualification/<int:pk>', views.qualification_detail),
    path('api/doctor/', views.doctor_list),
    path('api/doctor/<int:pk>', views.doctor_detail),
    path('api/administrator/', views.administrator_list),
    path('api/administrator/<int:pk>', views.administrator_detail),
    path('api/prescription/', views.prescription_list),
    path('api/prescription/<int:pk>', views.patient_detail),
    path('api/test/', views.test_list),
    path('api/test/<int:pk>', views.test_detail),
    path('api/appointment/', views.appointment_list),
    path('api/appointment/<int:pk>', views.appointment_detail),
    path('api/message/', views.message_list),
    path('api/message/<int:pk>', views.message_detail),
    path('api/logininfo/', views.logininfo_list),
    path('api/logininfo/<int:pk>', views.logininfo_detail),
    path('api/emergencyservice/', views.emergencyservices_list),
    path('api/emergencyservice/<int:pk>', views.emergencyservices_detail),
    path('api/ambulance/', views.ambulance_list),
    path('api/ambulance/<int:pk>', views.ambulance_detail),
    path('api/login/', views.login_list),
    path('api/login/<int:pk>', views.login_detail),
    path('api/bloodbankcenter/', views.bloodbankcenter_list),
    path('api/bloodbankcenter/<int:pk>', views.bloodbankcenter_detail),
    path('api/dispensaries/', views.dispensaries_list),
    path('api/dispensaries/<int:pk>', views.dispensaries_detail),
    path('api/event/', views.event_list),
    path('api/event/<int:pk>', views.event_detail),
    path('api/bloodbilling/', views.bloodbilling_list),
    path('api/bloodbilling/<int:pk>', views.bloodbilling_detail),
    path('api/bloodwaste/', views.bloodwaste_list),
    path('api/bloodwaste/<int:pk>', views.bloodwaste_detail),
    path('api/medicine/', views.medicine_list),
    path('api/medicine/<int:pk>', views.medicine_detail),
    path('api/dispensarybilling/', views.dispensarybilling_list),
    path('api/dispensarybilling/<int:pk>', views.dispensarybilling_detail),
    path('api/ambulancebilling/', views.ambulancebilling_list),
    path('api/ambulancebilling/<int:pk>', views.ambulancebilling_detail),
    path('api/testcentre/', views.testcentre_list),
    path('api/testcentre/<int:pk>', views.testcentre_detail),
    path('api/testservices/', views.testservices_list),
    path('api/testservices/<int:pk>', views.testservices_detail),
    path('api/webcarousel/', views.webcarousel_list),
    path('api/webcarousel/<int:pk>', views.webcarousel_detail),
    path('api/notice/', views.notice_list),
    path('api/notice/<int:pk>', views.notice_detail),

]
