# Generated by Django 2.0.9 on 2018-11-04 11:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MDTouch', '0002_auto_20181103_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodtype', models.CharField(default='', max_length=3)),
                ('bloodquantity', models.IntegerField(default=0, max_length=4)),
                ('date', models.DateField(default=datetime.datetime(2018, 11, 4, 11, 24, 51, 450133, tzinfo=utc))),
                ('patid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='TestCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=40)),
                ('city', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='emergencyservice',
            name='ambulance_id',
        ),
        migrations.AddField(
            model_name='ambulance',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.EmergencyService'),
        ),
        migrations.AddField(
            model_name='bloodbankcenter',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Login'),
        ),
        migrations.AddField(
            model_name='dispensaries',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Login'),
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expirydate',
            field=models.DateField(default=datetime.datetime(2018, 11, 4, 11, 24, 51, 447141, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturedate',
            field=models.DateField(default=datetime.datetime(2018, 11, 4, 11, 24, 51, 447141, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 4)),
        ),
        migrations.AddField(
            model_name='test',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.TestCentre'),
        ),
    ]
