# Generated by Django 2.0.9 on 2018-12-12 02:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MDTouch', '0003_auto_20181104_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField(default='', max_length=100)),
                ('kilometers', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2018, 12, 12, 8, 18, 44, 993892))),
                ('ambulance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Ambulance')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='BloodWaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('bloodgrp', models.CharField(default='', max_length=5)),
                ('reason', models.TextField(default='', max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bbcid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDTouch.BloodBankCenter')),
            ],
        ),
        migrations.CreateModel(
            name='DispensaryBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TestServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.RenameField(
            model_name='dispensaries',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='dispensaries',
            name='medicine',
        ),
        migrations.AddField(
            model_name='appointment',
            name='dateofrequest',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bloodbilling',
            name='Eventid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Event'),
        ),
        migrations.AddField(
            model_name='bloodbilling',
            name='bbcid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.BloodBankCenter'),
        ),
        migrations.AddField(
            model_name='bloodbilling',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispensaries',
            name='address',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dispensaries',
            name='city',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='dispensaries',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='bloodbankid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MDTouch.BloodBankCenter'),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='event',
            name='dateofcreation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='dateofevent',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='dispensaryid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MDTouch.Dispensaries'),
        ),
        migrations.AddField(
            model_name='event',
            name='hospitalid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MDTouch.Hospital'),
        ),
        migrations.AddField(
            model_name='event',
            name='testcentreid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MDTouch.TestCentre'),
        ),
        migrations.AddField(
            model_name='event',
            name='totalregistered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dispensary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MDTouch.Dispensaries'),
        ),
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bloodbilling',
            name='bloodquantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bloodbilling',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.AlterField(
            model_name='event',
            name='eventlocation',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expirydate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturedate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dispensarybilling',
            name='dispensaryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Dispensaries'),
        ),
        migrations.AddField(
            model_name='dispensarybilling',
            name='eventid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Event'),
        ),
        migrations.AddField(
            model_name='dispensarybilling',
            name='medicineid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Medicine'),
        ),
        migrations.AddField(
            model_name='dispensarybilling',
            name='patientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.ManyToManyField(to='MDTouch.qualification'),
        ),
        migrations.AddField(
            model_name='testcentre',
            name='tests',
            field=models.ManyToManyField(to='MDTouch.TestServices'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ManyToManyField(to='MDTouch.specialization'),
        ),
    ]
