# Generated by Django 2.0.9 on 2018-12-12 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDTouch', '0005_auto_20181212_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancebilling',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 12, 9, 4, 50, 294660)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phase',
            field=models.CharField(default='', max_length=10),
        ),
    ]
