# Generated by Django 2.0.9 on 2018-12-12 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDTouch', '0008_auto_20181212_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancebilling',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 12, 12, 16, 40, 143790)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.ManyToManyField(to='MDTouch.Qualification'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ManyToManyField(to='MDTouch.Specialization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='picurl',
            field=models.CharField(default='', max_length=800, null=True),
        ),
    ]
