# Generated by Django 2.0.9 on 2018-12-12 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDTouch', '0010_auto_20181212_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancebilling',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 12, 12, 18, 9, 550553)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.ManyToManyField(to='MDTouch.Qualification'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ManyToManyField(to='MDTouch.Specialization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
    ]
