# Generated by Django 2.0.9 on 2018-12-12 14:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDTouch', '0012_auto_20181212_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancebilling',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 12, 19, 51, 21, 239636)),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='qualification',
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Qualification'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Specialization'),
        ),
        migrations.RemoveField(
            model_name='testcentre',
            name='tests',
        ),
        migrations.AddField(
            model_name='testcentre',
            name='tests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.TestServices'),
        ),
    ]
