# Generated by Django 2.0.9 on 2018-12-16 19:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDTouch', '0013_auto_20181212_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='Health Ministry', max_length=100)),
                ('notice', models.TextField(default='Important notice', max_length=400)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 12, 17, 1, 20, 24, 848392))),
            ],
        ),
        migrations.CreateModel(
            name='WebCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(default='Welcome', max_length=30)),
                ('url', models.CharField(default='img not found', max_length=800)),
                ('slug', models.CharField(default='HealthCare', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='ambulancebilling',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 1, 20, 24, 847395)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Qualification'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Specialization'),
        ),
    ]
