# Generated by Django 2.0.9 on 2018-12-22 22:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDTouch', '0014_auto_20181217_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbankcenter',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='emergencyservice',
            name='state',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Login'),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='ambulancebilling',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 4, 8, 44, 599031)),
        ),
        migrations.AlterField(
            model_name='bloodbankcenter',
            name='contact',
            field=models.IntegerField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Qualification'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Specialization'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Login'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='emergencyservice',
            name='city',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='emergencyservice',
            name='contact_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contact',
            field=models.IntegerField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 4, 8, 44, 600078)),
        ),
    ]
