# Generated by Django 2.0.9 on 2018-12-23 23:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDTouch', '0018_auto_20181223_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestaddress', models.CharField(default='', max_length=200)),
                ('arrivalpin', models.IntegerField(default=0)),
                ('destinationpin', models.IntegerField(default=0, null=True)),
                ('destinationaddress', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=500)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 12, 24, 4, 47, 34, 9828))),
                ('sendto', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiverDelete',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiverName',
        ),
        migrations.RemoveField(
            model_name='message',
            name='senderDelete',
        ),
        migrations.RemoveField(
            model_name='message',
            name='senderName',
        ),
        migrations.RemoveField(
            model_name='message',
            name='senderType',
        ),
        migrations.RemoveField(
            model_name='message',
            name='viewed',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodbankcenter',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodbankcenter',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dispensaries',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergencyservice',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergencyservice',
            name='state',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='emergencyservice',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Login'),
        ),
        migrations.AddField(
            model_name='event',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='message',
            name='senderid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Login'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='testcentre',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ambulancebilling',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 4, 47, 34, 11822)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Qualification'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Specialization'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 4, 47, 34, 9828)),
        ),
        migrations.AddField(
            model_name='ambulancerequest',
            name='patid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Patient'),
        ),
        migrations.AddField(
            model_name='ambulancebilling',
            name='requestid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.AmbulanceRequest'),
        ),
    ]
