# Generated by Django 2.0.9 on 2018-12-24 19:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDTouch', '0020_auto_20181225_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensaries',
            name='regno',
        ),
        migrations.AddField(
            model_name='dispensaries',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Login'),
        ),
        migrations.AlterField(
            model_name='ambulancebilling',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 1, 22, 53, 777381)),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 1, 22, 53, 775534)),
        ),
        migrations.AlterField(
            model_name='dispensaries',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Qualification'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Specialization'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 1, 22, 53, 774389)),
        ),
    ]
