# Generated by Django 2.0.9 on 2019-01-01 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDTouch', '0022_auto_20181230_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='EMP', max_length=4)),
                ('type', models.CharField(default='single bed', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='BedBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkindate', models.DateTimeField(default=datetime.datetime(2019, 1, 1, 17, 4, 59, 263049))),
                ('checkoutdate', models.DateTimeField(default=datetime.datetime(2019, 1, 1, 17, 4, 59, 263049))),
                ('bedid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MDTouch.Bed')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2019, 1, 1, 17, 4, 59, 265992))),
                ('appointmentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MDTouch.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='MaintainenceBed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField(default=datetime.datetime(2019, 1, 1, 17, 4, 59, 263998))),
                ('enddate', models.DateTimeField(default=datetime.datetime(2019, 1, 1, 17, 4, 59, 263998))),
                ('message', models.CharField(default='Under manintainence', max_length=80)),
                ('bedid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MDTouch.Bed')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='aadharnumber',
            field=models.CharField(default='6995-6666-6214', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(default='AB+', max_length=4),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='patient',
            name='dateofbirth',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 17, 4, 59, 221559)),
        ),
        migrations.AddField(
            model_name='patient',
            name='maritalstatus',
            field=models.CharField(default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='smokinghabit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ambulancebilling',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 17, 4, 59, 261029)),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 17, 4, 59, 258463)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Qualification'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Specialization'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 17, 4, 59, 258463)),
        ),
        migrations.AddField(
            model_name='hospitalbilling',
            name='doctorid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MDTouch.Doctor'),
        ),
        migrations.AddField(
            model_name='hospitalbilling',
            name='hospitalid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MDTouch.Hospital'),
        ),
        migrations.AddField(
            model_name='hospitalbilling',
            name='patientid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MDTouch.Patient'),
        ),
        migrations.AddField(
            model_name='hospitalbilling',
            name='prescriptionid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MDTouch.Prescription'),
        ),
        migrations.AddField(
            model_name='bedbilling',
            name='patientid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MDTouch.Patient'),
        ),
        migrations.AddField(
            model_name='bed',
            name='currentpatient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MDTouch.Patient'),
        ),
        migrations.AddField(
            model_name='bed',
            name='hospitalid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MDTouch.Hospital'),
        ),
    ]
