# Generated by Django 2.0.9 on 2019-01-04 19:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDTouch', '0023_auto_20190101_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseCured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2019, 1, 5, 0, 55, 36, 853518))),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2019, 1, 5, 0, 55, 36, 853518))),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Disease')),
            ],
        ),
        migrations.AlterField(
            model_name='ambulancebilling',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 0, 55, 36, 847570)),
        ),
        migrations.AlterField(
            model_name='bedbilling',
            name='checkindate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 0, 55, 36, 849587)),
        ),
        migrations.AlterField(
            model_name='bedbilling',
            name='checkoutdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 0, 55, 36, 849587)),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 0, 55, 36, 845540)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Qualification'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Specialization'),
        ),
        migrations.AlterField(
            model_name='hospitalbilling',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 0, 55, 36, 850580)),
        ),
        migrations.AlterField(
            model_name='maintainencebed',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 0, 55, 36, 850499)),
        ),
        migrations.AlterField(
            model_name='maintainencebed',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 0, 55, 36, 849587)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 0, 55, 36, 845540)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dateofbirth',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 0, 55, 36, 799635)),
        ),
        migrations.AddField(
            model_name='diseasecured',
            name='patientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Patient'),
        ),
    ]
